site_name: Cursor-Utils
site_description: Give your Cursor Agent superpowers
site_author: gweidart
repo_url: https://github.com/gweidart/cursor-utils
repo_name: gweidart/cursor-utils
docs_dir: docs
copyright: Copyright &copy; 2025 gweidart

theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/images/cursor-utils-logo.svg
  favicon: assets/images/favicon.svg
  icon:
    repo: fontawesome/brands/github
  palette:
    scheme: darkula
  font:
    text: JetBrains Mono
    code: JetBrains Mono
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - content.code.annotate
    - content.tabs.link
    - toc.follow
    - search.suggest
    - search.highlight
    - header.autohide
    - navigation.footer

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets:
      base_path: $config_dir
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - toc:
      permalink: true
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - macros
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_source: true
            show_submodules: true
            docstring_style: google
            docstring_section_style: spacy

# Navigation structure
nav:
  - Home: index.md
  - Getting Started:
    - Installation: installation.md
    - Usage: usage.md
  - Commands:
    - config: commands/config.md
    - gemini: commands/gemini.md
    - github: commands/github.md
    - project: commands/project.md
    - repo: commands/repo.md
    - web: commands/web.md
  - API Reference:
    - Overview: api/index.md
    - CLI: api/cli.md
    - Commands: api/commands.md
    - Configuration: api/config.md
    - Models: api/models.md
    - Utilities: api/utils.md
  - Troubleshooting:
    - Common Errors: errors/index.md
  - Development:
    - Contributing: contributing.md
  - License: license.md

# Extra configuration
extra:
  version: {0.1.5}
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/gweidart/cursor-utils
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/cursor-utils/
  generator: false

# Ensure all internal links are treated as absolute from the docs root
use_directory_urls: false

extra_css:
  - stylesheets/extra.css
