site_name: Cursor-Utils
site_description: Enhanced capabilities for Cursor IDE Agents
site_author: gweidart
repo_url: https://github.com/gweidart/cursor-utils
repo_name: gweidart/cursor-utils

theme:
  name: material
  palette:
    # Palette toggle for dark mode (primary)
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      
    # Palette toggle for light mode (secondary)
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  
  # Rose Pine Moon custom colors
  custom_dir: docs/overrides
  
  # Logo and favicon
  logo: assets/images/cursor-utils-logo.svg
  favicon: assets/images/favicon.svg
  icon:
    repo: fontawesome/brands/github
  
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - content.code.annotate
    - content.tabs.link
    - toc.follow
    - search.suggest
    - search.highlight
    - header.autohide
    - navigation.footer

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - toc:
      permalink: true
  - attr_list
  - def_list
  - md_in_html

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_source: true
            show_submodules: true
            docstring_style: google
            docstring_section_style: spacy

# Extra configuration
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/gweidart/cursor-utils
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/cursor-utils/
  generator: false

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - API Reference:
    - Overview: api/index.md
    - CLI: api/cli.md
    - Commands: 
      - Overview: api/commands.md
      - Config: api/commands/config.md
      - Gemini: api/commands/gemini.md
      - GitHub: api/commands/github.md
      - Web: api/commands/web.md
      - Project: api/commands/project.md
      - Repo: api/commands/repo.md
    - Configuration: api/config.md
    - Utilities: api/utils.md
    - Models: api/models.md
  - Error Reference:
    - Overview: errors/index.md
  - Contributing: contributing.md
  - License: license.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            show_root_heading: true
            heading_level: 3 